spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_db
    username: aura_user
    password: aura_pass123
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: 4a6f686e576f6f644469644d65616e57686174596f754d6164654d654665656c4c696b65416e496e737069726f
    expiration-ms: 86400000

server:
  port: 8085
