spring:
  application:
    name: chat-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chat_db}
    username: ${SPRING_DATASOURCE_USERNAME:aura_user}
    password: ${SPRING_DATASOURCE_PASSWORD:aura_pass123}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${APP_JWT_SECRET:4a6f686e576f6f644469644d65616e57686174596f754d6164654d654665656c4c696b65416e496e737069726f}
    expiration-ms: 86400000

server:
  port: 8085
